{{- if and (eq .Values.config.notify "true") (eq .Values.config.storeNotifications "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: check-christmas-lottery-numbers-mongo-secret
  labels:
    app: check-christmas-lottery-numbers-mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.config.mongodb.rootCredentials.username | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.config.mongodb.rootCredentials.password | b64enc }}
{{- end }}