{{- if and (eq .Values.config.notify "true") (eq .Values.config.storeNotifications "true") }}
apiVersion: v1
kind: Service
metadata:
  name: check-christmas-lottery-numbers-mongo
  labels:
    app: check-christmas-lottery-numbers-mongo
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: check-christmas-lottery-numbers-mongo
{{- end }}