# Default values for check-cPUSH_OVER_NOTIFICATION_TOKENhristmas-lottery-numbers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: xoanmallon/check-christmas-lottery-numbers
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.1.6
imageCredentials:
  url: ""
  username: ""
  password: ""
  name: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
config:
  lotteryDraw: "christmas"
  push_over_notification_token: ""
  push_over_notification_user: ""
  notify: "true"
  storeNotifications: "false"
  minutesSchedulePeriod: ""
  mongodb:
    rootCredentials:
      username: ""
      password: ""
    storage:
      className: ""
      size: 512Mi
