apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "check-christmas-lottery-numbers.fullname" . }}-config
  labels:
    {{- include "check-christmas-lottery-numbers.labels" . | nindent 4 }}
data:
  numbers_to_check.json: |-
{{ .Files.Get "numbers_to_check.json" | indent 4}}