apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "check-christmas-lottery-numbers.fullname" . }}
  labels: {{- include "check-christmas-lottery-numbers.labels" . | nindent 4 }}
spec:
  jobTemplate:
    metadata:
      name: check-christmas-lottery-numbers
      labels:
        {{- include "check-christmas-lottery-numbers.labels" . | nindent 8 }}
    spec:
      template:
        spec:
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
              name: check-christmas-lottery-numbers
              {{- if eq .Values.config.notify true }}
              command:
                - "./check-christmas-lottery-numbers"
                - "-n"
              env:
                - name: PUSH_OVER_NOTIFICATION_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "check-christmas-lottery-numbers.fullname" . }}-secret
                      key: PUSH_OVER_NOTIFICATION_TOKEN
                - name: PUSH_OVER_NOTIFICATION_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "check-christmas-lottery-numbers.fullname" . }}-secret
                      key: PUSH_OVER_NOTIFICATION_USER
              {{- end }}
              volumeMounts:
              - name: config-volume
                mountPath: /tmp/
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "check-christmas-lottery-numbers.fullname" . }}-config
          restartPolicy: OnFailure
          {{ if .Values.imageCredentials.password }}
          imagePullSecrets:
            - name: {{ .Values.imageCredentials.name }}
          {{ end }}
  {{- if .Values.config.minutesSchedulePeriod }}
  schedule: '*/{{ .Values.config.minutesSchedulePeriod}} * * * *'
  {{- else }}
  schedule: '*/10 * * * *'
  {{- end}}