apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "check-christmas-lottery-numbers.fullname" . }}
  labels: {{- include "check-christmas-lottery-numbers.labels" . | nindent 4 }}
spec:
  jobTemplate:
    metadata:
      name: check-christmas-lottery-numbers
      labels:
        {{- include "check-christmas-lottery-numbers.labels" . | nindent 8 }}
    spec:
      template:
        spec:
          {{- if eq .Values.config.notify "true" }}
          initContainers:
            - name: wait-mongo
              image: busybox:1.28
              command: ['sh', '-c', 'until wget --spider -S check-christmas-lottery-numbers-mongo:27017; do echo waiting for check-christmas-lottery-numbers-mongo; sleep 2; done']
          {{- end }}
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
              name: check-christmas-lottery-numbers
              {{- if eq .Values.config.notify "true" }}
              command:
                - "./check-christmas-lottery-numbers"
                - "-n"
                - "-d={{ .Values.config.lotteryDraw }}"
                {{- if and (eq .Values.config.notify "true") (eq .Values.config.storeNotifications "true")}}
                - "-s"
                - "-m=check-christmas-lottery-numbers-mongo:27017"
                {{- end }}
              {{- end }}
              {{- if eq .Values.config.notify "true" }}
              envFrom:
                - secretRef:
                    name: {{ include "check-christmas-lottery-numbers.fullname" . }}-secret
                {{- if eq .Values.config.storeNotifications "true"}}
                - secretRef:
                    name: check-christmas-lottery-numbers-mongo-secret
                {{- end }}
              {{- end }}
              volumeMounts:
              - name: config-volume
                mountPath: /tmp/
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "check-christmas-lottery-numbers.fullname" . }}-config
          restartPolicy: OnFailure
          {{ if .Values.imageCredentials.password }}
          imagePullSecrets:
            - name: {{ .Values.imageCredentials.name }}
          {{ end }}
  {{- if .Values.config.minutesSchedulePeriod }}
  schedule: '*/{{ .Values.config.minutesSchedulePeriod}} * * * *'
  {{- else }}
  schedule: '*/10 * * * *'
  {{- end }}