{{- if eq .Values.config.notify "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "check-christmas-lottery-numbers.fullname" . }}-secret
  labels:
  {{- include "check-christmas-lottery-numbers.labels" . | nindent 4 }}
data:
  PUSH_OVER_NOTIFICATION_TOKEN: {{ .Values.config.push_over_notification_token | b64enc }}
  PUSH_OVER_NOTIFICATION_USER: {{ .Values.config.push_over_notification_user | b64enc  }}
{{- end }}