name: Publish release

on:
  release:
    types: [published, created]

jobs:
  publish-version:
    name: PublishVersion
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.COMMIT_KEY }}"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            xoanmallon/check-christmas-lottery-numbers:${{ steps.get_version.outputs.VERSION }}
            xoanmallon/check-christmas-lottery-numbers:latest

      - name: Run GoReleaser
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: ./.github/actions/goreleaser