name: Publish release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-version:
    name: PublishVersion
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            xoanmallon/check-christmas-lottery-numbers:${{ github.GITHUB_REF_NAME }}
            xoanmallon/check-christmas-lottery-numbers:latest

      - name: Run GoReleaser
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: ./.github/actions/goreleaser