name: Release

on:
  workflow_run:
    workflows:
      - "Test"
    branches: [ main ]
    types:
      - completed

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Setup yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        env:
          YQ_VERSION: "3.4.1"

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug