name: Release

on:
  workflow_run:
    workflows:
      - "Test"
    branches: [ main ]
    types:
      - completed

jobs:
  semantic-release:
    if: "${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.commits[0].message, 'chore(release):') }}"
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Setup yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        env:
          YQ_VERSION: "3.4.1"

      - name: Setup helm
        run: |
          mkdir /tmp/helm
          wget -O /tmp/helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
          tar -xvf /tmp/helm/helm-v${HELM_VERSION}-linux-amd64.tar.gz -C /tmp/helm/
          sudo mv /tmp/helm/linux-amd64/helm /usr/local/bin/helm
          sudo rm -rf /tmp/helm/
          sudo chmod +x /usr/local/bin/helm
        env:
          HELM_VERSION: "3.7.1"

      - name: Create empty semantic_release_version.txt file
        run: touch semantic_release_version.txt

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::$(cat semantic_release_version.txt)

      - name: Set up Go
        if: ${{ steps.get_version.outputs.VERSION != '' }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Run GoReleaser
        if: ${{ steps.get_version.outputs.VERSION != '' }}
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v1
        if: ${{ steps.get_version.outputs.VERSION != '' }}

      - name: Login to DockerHub Registry
        if: ${{ steps.get_version.outputs.VERSION != '' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ steps.get_version.outputs.VERSION != '' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            xoanmallon/check-christmas-lottery-numbers:${{ steps.get_version.outputs.VERSION }}
            xoanmallon/check-christmas-lottery-numbers:latest

      - name: Run GoReleaser
        if: ${{ steps.get_version.outputs.VERSION != '' && steps.semantic.outputs.new_release_published == 'true' }}
        uses: ./.github/actions/goreleaser

      # Get release information to determine id of the current release
      - name: Get release info
        id: get-release-info
        uses: kaliber5/action-get-release@v1
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}

      # Upload helm chart tgz file to GitHub release
      - name: Upload Deployment helm chart tgz file
        if: ${{ steps.get_version.outputs.VERSION != '' }}
        id: upload-helm-chart-tgz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/xoanmallon/check-christmas-lottery-numbers/releases/${{ steps.get-release-info.outputs.id }}/assets?name=check-christmas-lottery-numbers-${{ steps.get_version.outputs.VERSION }}.tgz
          asset_path: /tmp/check-christmas-lottery-numbers-${{ steps.get_version.outputs.VERSION }}.tgz
          asset_name: check-christmas-lottery-numbers-${{ steps.get_version.outputs.VERSION }}.tgz
          asset_content_type: application/gzip