on:
  workflow_run:
    workflows:
      - "Lint"
    branches:
      - '*'
    types:
      - completed


name: Test
jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        go-version: [ 1.14.x ]
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test -coverprofile="${{ matrix.platform }}_coverage.out" -covermode=atomic -coverpkg=./... ./...
          go tool cover -func="${{ matrix.platform }}_coverage.out"
        env:
          PUSH_OVER_NOTIFICATION_TOKEN: ${{ secrets.PUSH_OVER_NOTIFICATION_TOKEN }}
          PUSH_OVER_NOTIFICATION_USER: ${{ secrets.PUSH_OVER_NOTIFICATION_USER }}